services:
  frontend:
    image: ghcr.io/sipioteo/rotaractrivoli-frontend:main
    container_name: rotaract-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:1337}
    restart: unless-stopped

  backend:
    image: ghcr.io/sipioteo/rotaractrivoli-backend:main
    container_name: rotaract-backend
    ports:
      - '1337:1337'
    volumes:
      - ./backend-data/uploads:/opt/app/public/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME:-strapi}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-strapi}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - APP_KEYS=${APP_KEYS}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - STRIPE_SK=${STRIPE_SK}
      - STRIPE_PK=${STRIPE_PK}
    depends_on:
      - db
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536

  db:
    image: postgres:16-alpine
    container_name: rotaract-db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-strapi}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME:-strapi}
    volumes:
      - strapi-prod-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  strapi-prod-data:
